FROM node:20-alpine AS builder

RUN corepack enable
WORKDIR /server

COPY . .
RUN pnpm install --frozen-lockfile
RUN pnpm --filter @dtc/backend build

FROM node:20-alpine AS runtime

RUN corepack enable
WORKDIR /app

COPY --from=builder /server/apps/backend/.medusa/server ./

RUN pnpm install --prod --frozen-lockfile

ENV NODE_ENV=production
EXPOSE 9000

CMD ["pnpm", "start"]